import React, { useState, useEffect } from 'react';
import MarketTrends from './components/MarketTrends';
import AnalysisEngine from './components/AnalysisEngine';
import SentimentFeed from './components/SentimentFeed';

const App: React.FC = () => {
  // States to stagger component mounting
  const [loadSecondary, setLoadSecondary] = useState(false);

  useEffect(() => {
    // Delay secondary API calls by 3 seconds to avoid 429 errors
    const timer = setTimeout(() => {
      setLoadSecondary(true);
    }, 3000);
    
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="min-h-screen p-4 md:p-6 lg:p-8 font-sans bg-slate-900 text-slate-200">
      <header className="mb-8 flex flex-col md:flex-row md:justify-between md:items-center border-b border-slate-700 pb-4">
        <div>
          <h1 className="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">
            TradeNexus AI
          </h1>
          <p className="text-slate-400 mt-1 text-sm">Daily Trading Support & Automated Technical Analysis</p>
        </div>
        <div className="mt-4 md:mt-0 flex space-x-4 text-xs text-slate-500">
           <div className="flex items-center space-x-1">
             <span className="w-2 h-2 bg-green-500 rounded-full"></span>
             <span>System Operational</span>
           </div>
           <div className="flex items-center space-x-1">
             <span className="font-mono">API: v1.0.2</span>
           </div>
        </div>
      </header>

      <main className="grid grid-cols-1 xl:grid-cols-4 gap-6">
        
        {/* Left Column: Analysis Engine (Loads Immediately) */}
        <section className="xl:col-span-3 space-y-6">
          <AnalysisEngine />
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
             {/* Staggered Loading for Sentiment Feed */}
             {loadSecondary ? (
               <SentimentFeed />
             ) : (
               <div className="bg-slate-800 p-6 rounded-lg animate-pulse text-slate-500 border border-slate-700">
                 Waiting for API slot...
               </div>
             )}

             <div className="bg-slate-800 p-6 rounded-lg border border-slate-700">
                <h3 className="text-white font-bold mb-3 border-b border-slate-700 pb-2 flex items-center space-x-2">
                   <svg className="w-5 h-5 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                   </svg>
                   <span>Active Watchlist Rules</span>
                </h3>
                <ul className="list-disc list-inside text-sm text-slate-300 space-y-2">
                   <li><strong className="text-indigo-400">SUI, SOL, BERA:</strong> Priority monitoring for intraday swings.</li>
                   <li><strong className="text-red-400">MACD Strategy:</strong> Wait for "Second Half Red Zone" on 1H chart for major trend confirmation.</li>
                   <li><strong className="text-green-400">Entry Execution:</strong> Execute on 15m positive histogram receding within the primary zone.</li>
                   <li><strong className="text-slate-500">Risk Management:</strong> Always set stop loss below the recent swing low.</li>
                </ul>
             </div>
          </div>
        </section>

        {/* Right Column: Market Trends (Staggered Loading) */}
        <section className="xl:col-span-1 h-full min-h-[500px]">
          {loadSecondary ? (
            <MarketTrends />
          ) : (
            <div className="h-full bg-slate-800 rounded-lg animate-pulse flex items-center justify-center text-slate-500">
              Queuing trends...
            </div>
          )}
        </section>

      </main>

      <footer className="mt-12 text-center text-xs text-slate-600 border-t border-slate-800 pt-6">
        <p className="mb-2 font-bold text-slate-500">RISK DISCLAIMER</p>
        <p className="max-w-4xl mx-auto">
          Trading cryptocurrencies involves significant risk and can result in the loss of your capital. 
          The analysis provided by this application is generated by AI based on historical technical patterns (MACD). 
          Real-time data grounding is used but may have latency.
        </p>
        <p className="mt-4">
          &copy; {new Date().getFullYear()} TradeNexus AI. All rights reserved.
        </p>
      </footer>
    </div>
  );
};

export default App;
